=name: "Example Server"
local_url: "http://localhost"
private_url: "http://192.168.4.23"
# public_url: "https://6105buttons3.olahmb.com"
public_url: "http://192.168.4.23"
port: "6996"
api_key: "asdf"
login_url_prefix: "asdf"
url_prefix: "asdf"
cookie_name: "example-server"
cookie_secret: "asdf"
cookie_secret_message: "why"
cookie_admin_name: "example-server-admin"
cookie_admin_secret: "asdf"
cookie_admin_secret_message: "why"
allow_origins_string: ""
admin_username: "asdf"
admin_password: "asdf"
time_zone: "America/New_York"
# save_files_path: "/home/morphs/SAVE_FILES"
save_files_path: "/Users/morpheous/WORKSPACE/GO/EXAMPLE_SERVER/SAVE_FILES"
bolt_db_path: "bolt.db"
encryption_key: "asdf"
log_level: "debug"
log_key: asdf
docker_name: "private-example-server"
git_url: "https://github.com/EXAMPLE_USER/EXAMPLE_SERVER.git"
git_ssh_url: "git@github.com:EXAMPLE_USER/EXAMPLE_SERVER.git"
go_version: "1.22.0"